### ISSUE TITLE
Тип данных под LBP

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#1]
В текущей реализации можно легко забыть/добавить одно или несколько значений в LBP. 
Предлагаю положить его в специальный класс, чтобы ничего нечаянно не сломать + спрятать туда все действия с LBP вроде кеширования и прочего.

**Comment by waryak** [comment]
вот тут непонятно, как правильно делать import

**Comment by waryak** [comment]
@slushkovsky  Вот ты говорил оставить там один класс, куда, по идее должны перейти большинство моих функций и действий main. Но в этот класс придется посылать тогда оочень много переменных. Так пойдет или все же стоит некоторые функции оставить вне класса болтаться как функция LBP, например?
