### ISSUE TITLE
Дублирующийся код

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#2]
```
for filename in dir_files_p:
        if filename.endswith('.jpg'): 
            samples.append(os.path.join(POSITIIVE_PATH, filename))  
            labels.append(1)     
    for filename in dir_files_n:
        if filename.endswith('.jpg'):  
            samples.append(os.path.join(NEGATIVE_PATH, filename))       
            labels.append(-1)
```

Данный код явно рожден сочетанием Ctrl+C, Ctrl+V
В таком случае очень легко что-то поправить в одном из мест и забыть продублировать в остальных. 

Как правило решается вынесением в функцию.

**Comment by waryak** [comment]
def data_create(dir_files,class_label,samples,labels):
        for filename in dir_files:
            if filename.endswith('.jpg'):
                samples.append(os.path.join(POSITIIVE_PATH,filename))
                labels.append(class_label)
        return
    
    data_create(dir_files_p, 1, samples, labels)
    data_create(dir_files_n, -1, samples, labels)

**Comment by waryak** [comment]
def data_create(dir_files,class_label,samples,labels):
        for filename in dir_files:
            if filename.endswith('.jpg'):
                if class_label==1:
                    samples.append(os.path.join(POSITIIVE_PATH,filename))
                if class_label==-1:
                    samples.append(os.path.join(NEGATIVE_PATH,filename))
                    labels.append(class_label)
        return
    
    data_create(dir_files_p, 1, samples, labels)
    data_create(dir_files_n, -1, samples, labels)
