### ISSUE TITLE
Шумный код

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#3]
При выполнении код всё время что то печает, даже если от него это не просишь. 
На уровне данного проекта это возможно ОК, но если потом интегрировать твоё решение в другие - будет куча вопросов с тем, что оно перекрывает действительно нужные выводы. 

Предлагаю спрятать дебажный вывод. 
Есть несколько вариантов: 

1. Писать их в лог (модуль logging) 
2. При помощи глоб. константы/переменной окружения/переменной функции включать или выключать печать дебажной инфы 

В идеале совместить эти  2 стратегии и сделать несколько режимов логгирования, например: 
- Поверхностный 
- Детальный 
- Избыточный

Такое решение позволит с легкостью дебаждить, даже не смотря на код.

**Comment by waryak** [comment]
пока ничо не понял, буду разбираться)
