### ISSUE TITLE
Названия файлов

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#4]
DataForming.py - CamelCase
detect.py - snake_case
svm.py - snake_case 

Не имею ничего против ни одного из стилей - на твой выбор, но выбери какой то один. 
В противном случае будет трудно ориентироваться в проекте.

**Comment by waryak** [comment]
DataForming->dataforming

**Comment by slushkovsky** [comment]
Скорее data_forming  тогда
