### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#5]
Предлагаю создать папку resources (или аналогичную), где будут хранится ресурсы: 
- Каскады Хаара
- Сетки 
- Обученный SVM 

В противном случае через пару недель будет очень много файлов и трудно будет найти нужный. 
+ Файлы ресурсов редко меняются.

**Comment by waryak** [comment]
Какие сетки? 
Как вывести обученный SVM?

**Comment by slushkovsky** [comment]
@waryak: Сетки будем потом обучать. Можно забрать сами опорные вектора и сохранить (пример получения есть у меня в плюсовом коде)

**Comment by waryak** [comment]
@slushkovsky  я не могу найти, как создать папку в репозитории:D Ты имел виду в репозитории создать? или создать НОВЫЕ репозитории?

**Comment by waryak** [comment]
И нет методов
get_support_vector_count()
в python кажется... Я просто использовал у себя те, что ты использовал у себя,а нагуглить по опорным векторам не удалось
