### ISSUE TITLE
RU comments

### ISSUE THREAD

**Issue by slushkovsky** [waryak/ComputerVision#9]
`with open(DATA_PATH) as f: # ДВУМЕРНЫЙ МАССИВ ПРЕВРАТИЛСЯ В ТРЕХМЕРНЫЙ:DD ТИПА НАШ ДВУМЕРНЫЙ МАССИВ ЭТО НУЛЕВОЙ ЭЛЕМЕНТ ТРЕХМЕРНОГО:D`

Такие комменты сломают работу почти всех консольных текстоных редакторов на компах без русской локализации + не русскоговорящим будет их не понять

**Comment by waryak** [comment]
убрал
